apiVersion: skaffold/v2beta20
kind: Config
metadata:
  name: my-skaffold-config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: v1nnyc/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: v1nnyc/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "pages/**/*.js"
            dest: .
    - image: v1nnyc/patients
      context: patients
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
